services:
  - type: web
    name: gerenciador-ar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "False"
    regions:
      - oregon
